import java.util.ArrayList;
public class MinHeapRunner{
  public static void main(String[] args){
    MinHeap<Integer> h = new MinHeap<Integer>(3);
    h.insert(3);
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.insert(2);
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.insert(1);
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.insert(4);
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.poll();
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.insert(1);
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.insert(5);
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.insert(6);
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.poll();
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.poll();
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.poll();
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.poll();
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.poll();
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(" peek(): " + h.peek());
    h.poll();
    System.out.print(h);
    System.out.print(" size: " + h.size());
    System.out.print(" isEmpty(): " + h.isEmpty());
    System.out.println(/* index out of bounds: " peek(): " + h.peek()*/);
  }
}
